name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from the workflow!"